databases:
  - name: post
    databaseName: post_i2bi
    user: post_i2bi_user

services:
  - type: web
    name: post
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: post_i2bi
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false